pool:
  name: Default  # Replace with your actual agent pool name
  demands:
    - Agent.OS -equals Windows  # Or Linux/Mac, based on your setup

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'gab-dotNetSP'
    appType: 'webAppLinux'
    appName: 'gab-webapp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
